FROM yanqd0/hugo as build

WORKDIR /src

COPY . .

EXPOSE 80

RUN hugo

FROM nginx:1.23.3-alpine
COPY --from=build /src/public/ /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]

